import { useState } from 'react';
import { fetchPoliceNews, AP_DISTRICTS } from './api/newsService';
import { summarizeNews } from './api/claudeService';

function BriefCard({ brief }) {
  return (
    <div style={{background: 'linear-gradient(135deg, #1e3a8a 0%, #1d4ed8 100%)'}} className="rounded-2xl p-6 mb-8 text-white shadow-xl">
      <div className="flex items-center gap-3 mb-5">
        <div className="w-10 h-10 rounded-xl bg-white/20 flex items-center justify-center text-xl">&#129302;</div>
        <div>
          <h2 className="font-bold text-lg">AI Intelligence Brief</h2>
          <p className="text-blue-200 text-xs">Generated by Groq Llama 3.3</p>
        </div>
        <div className="ml-auto w-3 h-3 rounded-full bg-green-400 animate-pulse" />
      </div>
      <pre className="text-base text-blue-50 whitespace-pre-wrap leading-relaxed font-sans">{brief}</pre>
    </div>
  );
}

function NewsCard({ article }) {
  const colorList = [
    'bg-blue-50 text-blue-700',
    'bg-purple-50 text-purple-700',
    'bg-green-50 text-green-700',
    'bg-orange-50 text-orange-700'
  ];
  const color = colorList[Math.floor(Math.random() * colorList.length)];
  return (
    <div className="bg-white border border-gray-100 rounded-2xl p-5 shadow-sm hover:shadow-lg transition-all hover:-translate-y-1 duration-200">
      <div className="flex items-start justify-between mb-3">
        <span className={color + ' text-xs px-3 py-1 rounded-full font-semibold'}>
          {article.source && article.source.name ? article.source.name : 'News'}
        </span>
        <span className="text-xs text-gray-300">
          {new Date(article.publishedAt).toLocaleDateString('en-IN', { day: 'numeric', month: 'short' })}
        </span>
      </div>
      <h3 className="text-base font-semibold text-gray-800 leading-snug mb-2 line-clamp-2">{article.title}</h3>
      <p className="text-sm text-gray-500 line-clamp-2 mb-4">{article.description}</p>
      <a href={article.url} target="_blank" rel="noopener noreferrer"
        className="text-sm text-blue-600 font-medium hover:underline">
        Read article &#8594;
      </a>
    </div>
  );
}

export default function App() {
  const [district, setDistrict] = useState('');
  const [news, setNews] = useState([]);
  const [brief, setBrief] = useState('');
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');
  const [generated, setGenerated] = useState(false);

  const generate = async () => {
    setLoading(true);
    setError('');
    setBrief('');
    setNews([]);
    try {
      const articles = await fetchPoliceNews(district);
      if (!articles.length) {
        setError('No news found. Try a different district or check your NewsAPI key.');
        setLoading(false);
        return;
      }
      setNews(articles);
      const summary = await summarizeNews(articles, district);
      setBrief(summary);
      setGenerated(true);
    } catch (err) {
      setError('Error: ' + err.message);
    }
    setLoading(false);
  };

  const today = new Date().toLocaleDateString('en-IN', {
    weekday: 'long', day: 'numeric', month: 'long', year: 'numeric'
  });

  return (
    <div className="min-h-screen bg-gray-50">

      <div style={{background: 'linear-gradient(135deg, #0f172a 0%, #1e3a8a 60%, #1d4ed8 100%)'}}>
        <div className="max-w-5xl mx-auto px-6 py-10">
          <div className="flex items-center gap-4 mb-6">
            <div className="w-14 h-14 rounded-2xl bg-white/10 border border-white/20 flex items-center justify-center text-3xl">
              &#128240;
            </div>
            <div>
              <h1 className="text-3xl font-bold text-white tracking-tight">News360AI</h1>
              <p className="text-blue-300 text-base mt-0.5">Intelligent News Monitoring Dashboard</p>
            </div>
            <div className="ml-auto text-right hidden sm:block">
              <p className="text-blue-300 text-sm">{today}</p>
              <div className="flex items-center gap-2 justify-end mt-1">
                <div className="w-2 h-2 rounded-full bg-green-400 animate-pulse" />
                <span className="text-green-400 text-xs font-medium">Live</span>
              </div>
            </div>
          </div>

          <div className="grid grid-cols-3 gap-3 mt-6">
            <div className="bg-white/10 border border-white/10 rounded-xl p-4 text-center">
              <p className="text-2xl font-bold text-white">{AP_DISTRICTS.length}</p>
              <p className="text-blue-300 text-xs mt-1">Districts</p>
            </div>
            <div className="bg-white/10 border border-white/10 rounded-xl p-4 text-center">
              <p className="text-2xl font-bold text-white">{news.length > 0 ? news.length : '--'}</p>
              <p className="text-blue-300 text-xs mt-1">Articles Found</p>
            </div>
            <div className="bg-white/10 border border-white/10 rounded-xl p-4 text-center">
              <p className="text-2xl font-bold text-white">{generated ? 'Yes' : '--'}</p>
              <p className="text-blue-300 text-xs mt-1">Brief Ready</p>
            </div>
          </div>
        </div>
      </div>

      <div className="max-w-5xl mx-auto px-6 py-8">

        <div className="bg-white border border-gray-100 rounded-2xl p-6 mb-8 shadow-sm">
          <div className="flex items-center gap-3 mb-4">
            <span className="text-2xl">&#127758;</span>
            <div>
              <h2 className="text-base font-bold text-gray-800">Select District</h2>
              <p className="text-sm text-gray-400">Choose a region to generate today's intelligence brief</p>
            </div>
          </div>
          <div className="flex flex-col sm:flex-row gap-3">
            <select value={district} onChange={e => setDistrict(e.target.value)}
              className="border border-gray-200 rounded-xl px-4 py-3 text-base text-gray-700 flex-1 focus:outline-none focus:ring-2 focus:ring-blue-500 bg-gray-50">
              <option value="">All Districts</option>
              {AP_DISTRICTS.map(d => (<option key={d} value={d}>{d}</option>))}
            </select>
            <button onClick={generate} disabled={loading}
              style={{background: loading ? '#93c5fd' : 'linear-gradient(135deg, #1e3a8a, #2563eb)'}}
              className="text-white px-8 py-3 rounded-xl text-base font-semibold shadow-md hover:shadow-lg disabled:cursor-not-allowed flex items-center gap-2 justify-center">
              {loading ? (
                <span className="flex items-center gap-2">
                  <span className="w-4 h-4 border-2 border-white border-t-transparent rounded-full animate-spin inline-block" />
                  Generating...
                </span>
              ) : (
                <span>&#9889; Generate Brief</span>
              )}
            </button>
          </div>
        </div>

        {error && (
          <div className="bg-red-50 border border-red-200 rounded-2xl p-5 mb-6 flex items-start gap-3">
            <span className="text-2xl">&#9888;</span>
            <p className="text-base text-red-700">{error}</p>
          </div>
        )}

        {loading && (
          <div className="text-center py-20">
            <div className="w-16 h-16 border-4 border-blue-600 border-t-transparent rounded-full animate-spin mx-auto mb-4" />
            <p className="text-base text-gray-500 font-medium">Fetching latest news...</p>
            <p className="text-sm text-gray-400 mt-1">AI is analyzing and generating brief</p>
          </div>
        )}

        {brief && <BriefCard brief={brief} />}

        {news.length > 0 && (
          <div>
            <div className="flex items-center gap-3 mb-5">
              <span className="text-2xl">&#128240;</span>
              <h2 className="text-xl font-bold text-gray-800">Source Articles</h2>
              <span className="bg-blue-100 text-blue-700 text-sm px-3 py-1 rounded-full font-semibold">{news.length} found</span>
              {district && (
                <span className="bg-purple-100 text-purple-700 text-sm px-3 py-1 rounded-full font-semibold">{district}</span>
              )}
            </div>
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-5">
              {news.map((article, i) => (<NewsCard key={i} article={article} />))}
            </div>
          </div>
        )}

        {!loading && !generated && (
          <div className="text-center py-24">
            <div className="text-7xl mb-6">&#127758;</div>
            <h3 className="text-2xl font-bold text-gray-700 mb-2">Ready to Monitor</h3>
            <p className="text-base text-gray-400 mb-1">Select a district and click Generate Brief</p>
            <p className="text-sm text-gray-300 mt-3">Powered by Groq Llama 3.3 + NewsAPI</p>
          </div>
        )}

        <div className="text-center mt-12 pb-6">
          <p className="text-sm text-gray-300">News360AI · Built with React + Groq AI + NewsAPI</p>
        </div>
      </div>
    </div>
  );
}
